name: realtime_obj_detection
description: An awesome flutter project to do real time object detection
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  tflite_v2: ^1.0.0
  camera: ^0.11.0
  provider: ^6.1.2
  google_maps_flutter: ^2.6.1
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  geolocator: ^14.0.2
  firebase_storage: ^11.6.5
  image: ^4.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/