// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8PYEc1Inpe6LliWQlydSiW4JFjUfCB_Y',
    appId: '1:349873090928:web:341e3cf642953a9d4b1fb5',
    messagingSenderId: '349873090928',
    projectId: 'jedsy-object-visualization',
    authDomain: 'jedsy-object-visualization.firebaseapp.com',
    storageBucket: 'jedsy-object-visualization.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCp1va71UiOZ9AhyGogIeqTQWopANxYpk',
    appId: '1:349873090928:android:465f993ba2a454e34b1fb5',
    messagingSenderId: '349873090928',
    projectId: 'jedsy-object-visualization',
    storageBucket: 'jedsy-object-visualization.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcij29FWaT1fQ7_s-nQVfMhrPMgBjy67A',
    appId: '1:349873090928:ios:6914b9154fd419a74b1fb5',
    messagingSenderId: '349873090928',
    projectId: 'jedsy-object-visualization',
    storageBucket: 'jedsy-object-visualization.firebasestorage.app',
    iosBundleId: 'com.example.jedsyObjectVisualization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcij29FWaT1fQ7_s-nQVfMhrPMgBjy67A',
    appId: '1:349873090928:ios:6914b9154fd419a74b1fb5',
    messagingSenderId: '349873090928',
    projectId: 'jedsy-object-visualization',
    storageBucket: 'jedsy-object-visualization.firebasestorage.app',
    iosBundleId: 'com.example.jedsyObjectVisualization',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8PYEc1Inpe6LliWQlydSiW4JFjUfCB_Y',
    appId: '1:349873090928:web:1bc6f3ac67893fe24b1fb5',
    messagingSenderId: '349873090928',
    projectId: 'jedsy-object-visualization',
    authDomain: 'jedsy-object-visualization.firebaseapp.com',
    storageBucket: 'jedsy-object-visualization.firebasestorage.app',
  );

}